FROM truecron/nvm
MAINTAINER Vitali Hatalski <vhatalski@naviam.com>

RUN curl -sL https://deb.nodesource.com/setup_0.12 | bash -

RUN npm install -g bower && \
    npm install -g mocha && \
    npm install -g ember-cli
